wandb_version: 1

activation_para:
  value: relu
batch:
  value: 32
epochs:
  value: 5
loss_function:
  value: cre
lr:
  value: 0.01
n_hidden_layers:
  value: 5
optimiser:
  value: adam
regularization:
  value: 'True'
s_hidden_layers:
  value: 64
weight_decay:
  value: 0.0005
weight_para:
  value: random
