wandb_version: 1

activation_para:
  value: sigmoid
batch:
  value: 64
epochs:
  value: 3
lr:
  value: 0.01
n_hidden_layers:
  value: 5
optimiser:
  value: nadam
s_hidden_layers:
  value: 128
weight_decay:
  value: 0
weight_para:
  value: Xavier
