wandb_version: 1

activation_para:
  value: relu
batch:
  value: 64
epochs:
  value: 10
lr:
  value: 0.001
n_hidden_layers:
  value: 5
optimiser:
  value: rms
s_hidden_layers:
  value: 64
weight_decay:
  value: 0.0005
weight_para:
  value: Xavier
