wandb_version: 1

activation_para:
  value: tanh
batch:
  value: 64
epochs:
  value: 3
lr:
  value: 0.001
n_hidden_layers:
  value: 5
optimiser:
  value: sgd
s_hidden_layers:
  value: 64
weight_decay:
  value: 0.0005
weight_para:
  value: Xavier
