wandb_version: 1

activation_para:
  value: tanh
batch:
  value: 32
epochs:
  value: 3
lr:
  value: 0
n_hidden_layers:
  value: 3
optimiser:
  value: adam
s_hidden_layers:
  value: 64
weight_para:
  value: Xavier
