wandb_version: 1

activation_para:
  value: sigmoid
batch:
  value: 32
epochs:
  value: 3
lr:
  value: 0.0005
n_hidden_layers:
  value: 3
optimiser:
  value: adam
s_hidden_layers:
  value: 32
weight_para:
  value: Xavier
