wandb_version: 1

activation_para:
  value: sigmoid
batch:
  value: 16
epochs:
  value: 5
lr:
  value: 0.001
n_hidden_layers:
  value: 5
optimiser:
  value: nadam
s_hidden_layers:
  value: 64
weight_decay:
  value: 0
weight_para:
  value: random
