sweep_configuration:
  method: bayes
  metric:
    name: val_loss
    goal: minimize
  parameters:
    epochs:
      values: [5, 10]
    n_hidden_layers:
      values: [3, 4, 5]
    s_hidden_layers:
      values: [32, 64, 128]
    weight_decay:
      values: [0, 0.0005, 0.5]
    lr:
      values: [0.001, 0.0001]
    optimiser:
      values: [sgd, mgd, nag, rms, adam, nadam]
    mini_batch_size:
      values: [16, 32, 64]
    weight_initialization:
      values: [random, Xavier]
    activations:
      values: [tanh, sigmoid, relu]
