wandb_version: 1

activation_para:
  value: tanh
batch:
  value: 16
epochs:
  value: 5
lr:
  value: 0.01
n_hidden_layers:
  value: 3
optimiser:
  value: sgd
s_hidden_layers:
  value: 64
weight_decay:
  value: 0.5
weight_para:
  value: Xavier
