wandb_version: 1

activation_para:
  value: tanh
batch:
  value: 16
epochs:
  value: 5
lr:
  value: 0
n_hidden_layers:
  value: 4
optimiser:
  value: nadam
s_hidden_layers:
  value: 32
weight_para:
  value: random
