wandb_version: 1

activation_para:
  value: sigmoid
batch:
  value: 32
epochs:
  value: 5
lr:
  value: 0.001
n_hidden_layers:
  value: 5
optimiser:
  value: adam
s_hidden_layers:
  value: 128
weight_decay:
  value: 0.0005
weight_para:
  value: random
