wandb_version: 1

activation_para:
  value: tanh
batch:
  value: 32
epochs:
  value: 10
lr:
  value: 0.001
n_hidden_layers:
  value: 3
optimiser:
  value: mgd
s_hidden_layers:
  value: 64
weight_decay:
  value: 0.5
weight_para:
  value: random
