wandb_version: 1

activation_para:
  value: sigmoid
batch:
  value: 32
epochs:
  value: 10
lr:
  value: 0.0001
n_hidden_layers:
  value: 5
optimiser:
  value: mgd
s_hidden_layers:
  value: 32
weight_decay:
  value: 0.0005
weight_para:
  value: random
