wandb_version: 1

activation_para:
  value: sigmoid
batch:
  value: 16
epochs:
  value: 10
lr:
  value: 0.0001
n_hidden_layers:
  value: 4
optimiser:
  value: mgd
s_hidden_layers:
  value: 64
weight_decay:
  value: 0
weight_para:
  value: Xavier
