wandb_version: 1

activation_para:
  value: sigmoid
batch:
  value: 16
epochs:
  value: 10
lr:
  value: 0.001
n_hidden_layers:
  value: 5
optimiser:
  value: sgd
s_hidden_layers:
  value: 128
weight_decay:
  value: 0.0005
weight_para:
  value: Xavier
