wandb_version: 1

activation_para:
  value: sigmoid
batch:
  value: 64
epochs:
  value: 10
lr:
  value: 0.001
n_hidden_layers:
  value: 5
optimiser:
  value: nag
s_hidden_layers:
  value: 128
weight_decay:
  value: 0.5
weight_para:
  value: Xavier
