wandb_version: 1

activation_para:
  value: relu
batch:
  value: 16
epochs:
  value: 5
lr:
  value: 0.001
n_hidden_layers:
  value: 4
optimiser:
  value: nadam
s_hidden_layers:
  value: 32
weight_decay:
  value: 0.0005
weight_para:
  value: random
