wandb_version: 1

activation_para:
  value: relu
batch:
  value: 32
epochs:
  value: 3
lr:
  value: 0.01
n_hidden_layers:
  value: 5
optimiser:
  value: adam
s_hidden_layers:
  value: 64
weight_decay:
  value: 0
weight_para:
  value: Xavier
