wandb_version: 1

activation_para:
  value: sigmoid
batch:
  value: 64
epochs:
  value: 5
lr:
  value: 0.0005
n_hidden_layers:
  value: 5
optimiser:
  value: rms_prop
s_hidden_layers:
  value: 128
weight_para:
  value: random
