wandb_version: 1

activation_para:
  value: tanh
batch:
  value: 32
epochs:
  value: 5
lr:
  value: 0
n_hidden_layers:
  value: 3
optimiser:
  value: rms_prop
s_hidden_layers:
  value: 32
weight_para:
  value: Xavier
