wandb_version: 1

activation_para:
  value: relu
batch:
  value: 16
epochs:
  value: 5
lr:
  value: 0.0005
n_hidden_layers:
  value: 4
optimiser:
  value: rms_prop
s_hidden_layers:
  value: 64
weight_para:
  value: random
