wandb_version: 1

activation_para:
  value: tanh
batch:
  value: 32
epochs:
  value: 5
lr:
  value: 0.0001
n_hidden_layers:
  value: 5
optimiser:
  value: rms
s_hidden_layers:
  value: 128
weight_decay:
  value: 0
weight_para:
  value: random
