wandb_version: 1

activation_para:
  value: relu
batch:
  value: 16
epochs:
  value: 3
loss_function:
  value: cre
lr:
  value: 0.001
n_hidden_layers:
  value: 4
optimiser:
  value: adam
regularization:
  value: 'True'
s_hidden_layers:
  value: 128
weight_decay:
  value: 0.5
weight_para:
  value: Xavier
