wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710002957.721398
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.10.12
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
activation_para:
  desc: null
  value: sigmoid
batch:
  desc: null
  value: 16
epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.01
n_hidden_layers:
  desc: null
  value: 5
optimiser:
  desc: null
  value: adam
s_hidden_layers:
  desc: null
  value: 64
weight_decay:
  desc: null
  value: 0.0005
weight_para:
  desc: null
  value: random
