wandb_version: 1

activation_para:
  value: sigmoid
batch:
  value: 16
epochs:
  value: 5
lr:
  value: 0.0001
n_hidden_layers:
  value: 3
optimiser:
  value: nag
s_hidden_layers:
  value: 64
weight_decay:
  value: 0.5
weight_para:
  value: random
