wandb_version: 1

activation_para:
  value: relu
batch:
  value: 64
epochs:
  value: 10
lr:
  value: 0.0001
n_hidden_layers:
  value: 3
optimiser:
  value: nadam
s_hidden_layers:
  value: 32
weight_decay:
  value: 0.0005
weight_para:
  value: Xavier
