wandb_version: 1

activation_para:
  value: tanh
batch:
  value: 16
epochs:
  value: 10
lr:
  value: 0.001
n_hidden_layers:
  value: 5
optimiser:
  value: rms
s_hidden_layers:
  value: 64
weight_decay:
  value: 0
weight_para:
  value: Xavier
