wandb_version: 1

activation_para:
  value: sigmoid
batch:
  value: 64
epochs:
  value: 5
lr:
  value: 0.0001
n_hidden_layers:
  value: 3
optimiser:
  value: adam
s_hidden_layers:
  value: 32
weight_decay:
  value: 0
weight_para:
  value: Xavier
