wandb_version: 1

activation_para:
  value: relu
batch:
  value: 64
epochs:
  value: 5
lr:
  value: 0.0001
n_hidden_layers:
  value: 5
optimiser:
  value: nadam
s_hidden_layers:
  value: 64
weight_decay:
  value: 0.5
weight_para:
  value: random
