wandb_version: 1

activation_para:
  value: sigmoid
batch:
  value: 32
epochs:
  value: 3
lr:
  value: 0.001
n_hidden_layers:
  value: 3
optimiser:
  value: nadam
s_hidden_layers:
  value: 128
weight_decay:
  value: 0.5
weight_para:
  value: Xavier
