wandb_version: 1

activation_para:
  value: relu
batch:
  value: 16
epochs:
  value: 3
lr:
  value: 0.0001
n_hidden_layers:
  value: 4
optimiser:
  value: rms_prop
s_hidden_layers:
  value: 128
weight_decay:
  value: 0.0005
weight_para:
  value: random
