wandb_version: 1

sweep_configuration:
  desc: null
  value:
    method: bayes
    metric:
      name: val_loss
      goal: minimize
    parameters:
      epochs:
        values:
        - 5
        - 10
      n_hidden_layers:
        values:
        - 3
        - 4
        - 5
      s_hidden_layers:
        values:
        - 32
        - 64
        - 128
      weight_decay:
        values:
        - 0
        - 0.0005
        - 0.5
      lr:
        values:
        - 0.001
        - 0.0001
      optimiser:
        values:
        - sgd
        - mgd
        - nag
        - rms
        - adam
        - nadam
      mini_batch_size:
        values:
        - 16
        - 32
        - 64
      weight_initialization:
        values:
        - random
        - Xavier
      activations:
        values:
        - tanh
        - sigmoid
        - relu
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709540308.461657
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
