wandb_version: 1

activation_para:
  value: relu
batch:
  value: 32
epochs:
  value: 5
lr:
  value: 0.0001
n_hidden_layers:
  value: 4
optimiser:
  value: sgd
s_hidden_layers:
  value: 128
weight_decay:
  value: 0
weight_para:
  value: random
