wandb_version: 1

activation_para:
  value: relu
batch:
  value: 64
epochs:
  value: 5
lr:
  value: 0.01
n_hidden_layers:
  value: 4
optimiser:
  value: rms_prop
s_hidden_layers:
  value: 128
weight_decay:
  value: 0.5
weight_para:
  value: Xavier
