wandb_version: 1

activation_para:
  value: relu
batch:
  value: 16
epochs:
  value: 3
lr:
  value: 0.0005
n_hidden_layers:
  value: 5
optimiser:
  value: nadam
s_hidden_layers:
  value: 32
weight_para:
  value: Xavier
